services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    ports:
      - "61975:8080"
    volumes:
      - spdf-trainingData:/usr/share/tessdata # Required for extra OCR languages
      - spdf-extraConfigs:/configs
      - spdf-customFiles:/customFiles/
      - spdf-logs:/logs/
      - spdf-pipeline:/pipeline/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=en_GB
volumes:
  spdf-trainingData:
  spdf-extraConfigs:
  spdf-customFiles:
  spdf-logs:
  spdf-pipeline:
