services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vaultwarden.netvar.org"
      WEBSOCKET_ENABLED: "true"
      # SIGNUPS_ALLOWED: "false"
      ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN}
      # Ek güvenlik ayarları
      ROCKET_WORKERS: 10
      EXTENDED_LOGGING: "true"
      LOG_LEVEL: warn
      # Rate limiting ayarları
      LOGIN_RATELIMIT_SECONDS: 60
      LOGIN_RATELIMIT_MAX_BURST: 10
      ADMIN_RATELIMIT_SECONDS: 300
      ADMIN_RATELIMIT_MAX_BURST: 3
      SQLITE_CACHE_SIZE: 8000 # SQLite önbellek boyutunu artırır
      SQLITE_SYNCHRONOUS: 1 # Normal güvenilirlik ile daha iyi performans
    volumes:
      - ./vw-data/:/data/
    ports:
      - "8011:80" # Nginx Proxy Manager üzerinden yönlendirme için
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/alive"]
      interval: 30s
      timeout: 10s
      retries: 3
