services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__DOMAIN=${DOMAIN}
      - GITEA__server__ROOT_URL==${ROOT_RUL}
      - GITEA__database__DB_TYPE=${DB_TYPE}
      - GITEA__database__HOST=${DB_HOST}
      - GITEA__database__NAME=${DB_NAME}
      - GITEA__database__USER=${DB_USER}
      - GITEA__database__PASSWD=${DB_PASS}
    ports:
      - "3763:3763" # Web UI
      - "2222:2222" # SSH (Git push/pull)
    volumes:
      - gitea_data:/data
    depends_on:
      - db
  db:
    image: postgres:16
    container_name: gitea-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - gitea_db:/var/lib/postgresql/data
volumes:
  gitea_data:
  gitea_db:
