version: "3.8"

services:
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # - "--api.dashboard=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      # - "./traefik.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"

  # webapp1:
  #   image: "your-webapp1-image:latest"
  #   container_name: "webapp1"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.webapp1.rule=Host(`webapp1.example.com`)"
  #     - "traefik.http.routers.webapp1.entrypoints=web"
  #     - "traefik.http.services.webapp1.loadbalancer.server.port=80"

  # webapp2:
  #   image: "your-webapp2-image:latest"
  #   container_name: "webapp2"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.webapp2.rule=Host(`webapp2.example.com`)"
  #     - "traefik.http.routers.webapp2.entrypoints=web"
  #     - "traefik.http.services.webapp2.loadbalancer.server.port=80"
