version: "3"

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    networks:
      - network1
    ports:
      - "5672:5672" # RabbitMQ port
      - "4449:15672" # RabbitMQ management UI port
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE} # Özel bir erlang cookie belirleyin
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER} # Kullanıcı adınızı belirleyin
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS} # Şifrenizi belirleyin
    volumes:
      - ./rabbitmqdata:/var/lib/rabbitmq # Verileri saklamak için bir volume oluşturun
networks:
  network1:
    name: sp_mysql_cluster
    external: true
