version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # AMQP
      - "${RABBITMQ_UI_PORT}:15672" # Management UI
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    networks:
      - network1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == ${TARGET_HOSTNAME}

volumes:
  rabbitmqdata:

networks:
  network1:
    external: true
    name: sp_mysql_cluster
