version: "3.3"
services:
  sftpgo:
    image: drakkan/sftpgo
    container_name: sftpgo
    volumes:
      - ./sftpgohome:/var/lib/sftpgo
      - ./sftpgodata:/srv/sftpgo
    ports:
      - "8880:8080"
      - "2022:2022"
      - "2121:2121"
      - "50000-50100:50000-50100"
    environment:
      SFTPGO_FTPD__BINDINGS__0__PORT: 2121
      SFTPGO_FTPD__BINDINGS__0__FORCE_PASSIVE_IP: 193.192.105.122
      SFTPGO_FTPD__PASSIVE_PORT_RANGE__START: 50000
      SFTPGO_FTPD__PASSIVE_PORT_RANGE__END: 50010
      SFTPGO_SFTPD__BINDINGS__0__PORT: 2022
      SFTPGO_WEBDAVD__BINDINGS__0__PORT: 8081 # WebDAV da açalım
      SFTPGO_COMMON__LOG_LEVEL: info # log seviyesi
      SFTPGO_HTTPD__BINDINGS__0__PORT: 8080
      SFTPGO_HTTPD__BINDINGS__0__PROXY_HEADERS__0: "X-Forwarded-For"
      SFTPGO_HTTPD__BINDINGS__0__PROXY_HEADERS__1: "X-Real-IP"
