version: "3.1"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mrrobot
      MONGO_INITDB_ROOT_PASSWORD: mrrobot
    volumes:
      - ./volume/data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mrrobot
      ME_CONFIG_MONGODB_ADMINPASSWORD: mrrobot
      ME_CONFIG_MONGODB_URL: mongodb://mrrobot:mrrobot@mongo:27017/
