version: "3.1"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mrrobot
      MONGO_INITDB_ROOT_PASSWORD: mrrobot
    volumes:
      - ./volume/data:/data/db
      # - ./volume/config:/data/configdb
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mrrobot
      ME_CONFIG_MONGODB_ADMINPASSWORD: mrrobot
      ME_CONFIG_MONGODB_URL: mongodb://mrrobot:mrrobot@mongo:27017/
