version: "3.2"
services:
  db:
    image: mysql
    networks:
      - network1
    command:
      - --default-authentication-plugin=mysql_native_password
      - --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
      # - --max_connections=1000
      - --skip-log-bin
    restart: always
    ports:
      - 4445:3306
    volumes:
      - ./mysql8data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mrrobot
      MYSQL_USER: mrrobot
      MYSQL_PASSWORD: mrrobot
      TZ: Asia/Istanbul
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
  adminer:
    image: adminer
    restart: always
    ports:
      - 4446:8080
networks:
  network1:
    name: sp_mysql_cluster
    external: true
