version: "3.2"
services:
  db:
    image: mysql
    command:
      - --default-authentication-plugin=mysql_native_password
      - --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
      - --max_connections=10000
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql8_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mrrobot
      MYSQL_USER: mrrobot
      MYSQL_PASSWORD: mrrobot
      TZ: Asia/Istanbul
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
  adminer:
    image: adminer
    restart: always
    ports:
      - 3307:8080
volumes:
  mysql8_data:
