version: "3.3"
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    network_mode: "host"
    volumes:
      - ./portainer_data:/data:Z
    environment:
      - EDGE_INSECURE_POLL=1
