x-mysql-connections: &mysql-connections
  mysql-main: &mysql-main-connection "SERVER=${MYSQL_HOST};DATABASE=smartpower_db;UiD=root;PASSWORD=${MYSQL_ROOT_PASSWORD};PORT=3306;SslMode=none;default command timeout=2000;charset=utf8;AllowPublicKeyRetrieval=True"
  mysql-mqtt: &mysql-mqtt-connection "SERVER=${MYSQL_HOST};DATABASE=sp_mqtt_db;UiD=root;PASSWORD=${MYSQL_ROOT_PASSWORD};PORT=3306;SslMode=none;default command timeout=2000;charset=utf8;AllowPublicKeyRetrieval=True"

x-rabbitmq-settings: &rabbitmq-settings
  RabbitMQ__HostName: ${RABBITMQ_HOST}
  RabbitMQ__UserName: ${RABBITMQ_DEFAULT_USER}
  RabbitMQ__Password: ${RABBITMQ_DEFAULT_PASS}

x-mqtt-credentials: &mqtt-credentials
  mqtt-client-id: &mqtt-client-id ${MQTT_CLIENTID}
  mqtt-username: &mqtt-username ${MQTT_USERNAME}
  mqtt-password: &mqtt-password ${MQTT_PASSWORD}

x-mqtt-settings: &mqtt-settings
  Mqtt__ClientId: *mqtt-client-id
  Mqtt__UserName: *mqtt-username
  Mqtt__Password: *mqtt-password
  Mqtt__BrokerAddress: ${MQTT_BROKER_ADDRESS:-localhost}
  Mqtt__BrokerPort: ${MQTT_BROKER_PORT:-1883}

x-mqtt-server-settings: &mqtt-server-settings
  MQTT__Default__ClientId: *mqtt-client-id
  MQTT__Default__Username: *mqtt-username
  MQTT__Default__Password: *mqtt-password

x-mongodb-settings: &mongodb-settings
  ModemLogDatabaseSettings__ConnectionString: &mongodb-connection mongodb://${MONGODB_ROOT_USER}:${MONGODB_ROOT_PASSWORD}@${MONGODB_HOST}:27017
  ServiceLogDatabaseSettings__ConnectionString: *mongodb-connection
  TsLogDatabaseSettings__ConnectionString: *mongodb-connection
  ModemLogDatabaseSettings__DatabaseName: &mongodb-db-name "SmartPowerLog"
  ServiceLogDatabaseSettings__DatabaseName: *mongodb-db-name
  TsLogDatabaseSettings__DatabaseName: *mongodb-db-name
  ModemLogDatabaseSettings__ModemLogCollectionName: "ModemLog"
  ServiceLogDatabaseSettings__ServiceLogCollectionName: "ServiceLog"
  TsLogDatabaseSettings__TsLogCollectionName: "TsLog"

x-common-podman-service: &common-podman-service
  restart: always
  network_mode: "host"

x-dotnet-env: &dotnet-env
  TZ: Europe/Istanbul
  DOTNET_RUNNING_IN_CONTAINER: true
  DOTNET_VERSION: 9.0.6
  ASPNET_VERSION: 9.0.6
  LogType__RabbitMQ__Status: true
  LogType__File__Status: false
  LogType__File__Path: "/var/log/sp-iot"
  ConnectionStrings__Mysql: *mysql-main-connection
services:
  php-apache:
    <<: *common-podman-service
    image: docker.io/erte33/spweb-php74fpm-apache:production
    container_name: spweb-php-apache-production
    expose:
      - "4433"
      - "4447"
    volumes:
      - ./spweb-log-volume:/var/www/html/log/log_files:Z
      - ./spweb-uploads-volume:/var/www/html/uploads:Z
      - ./spweb-customreport-volume:/var/www/html/customReport/files:Z
      - ./spweb-exportfiles-volume:/var/www/html/exportFiles:Z
    env_file:
      - .env.web

  sp-iot:
    <<: *common-podman-service
    image: "docker.io/erte33/sp-iot:latest"
    depends_on:
      - waiter
    volumes:
      - ./entrypoint.sh:/App/entrypoint.sh:Z
    entrypoint: ["bash", "-c", "/App/entrypoint.sh 'IoT Device Manager.dll'"]
    expose:
      - "4444"
      - "54739"
    environment:
      <<: [*dotnet-env, *rabbitmq-settings, *mqtt-settings]
  sp-websocket:
    <<: *common-podman-service
    image: "docker.io/erte33/sp-websocket:latest"
    container_name: sp-websocket
    environment:
      <<: [*dotnet-env, *rabbitmq-settings, *mqtt-settings, *mongodb-settings]
    volumes:
      - ./entrypoint.sh:/App/entrypoint.sh:Z
    entrypoint: ["bash", "-c", "/App/entrypoint.sh GrupArGe.SmartPower.WebSocket.dll"]
    expose:
      - "5057"

  sp-rabbitmqtodb:
    <<: *common-podman-service
    image: "docker.io/erte33/sp-rabbitmqtodb:latest"
    volumes:
      - ./entrypoint.sh:/App/entrypoint.sh:Z
    entrypoint: ["bash", "-c", "/App/entrypoint.sh GrupArGe.RabbitMQToDB.dll"]
    environment:
      <<: [*dotnet-env, *rabbitmq-settings, *mqtt-settings, *mongodb-settings]
      RabbitMQ__PreFetchCount__mail: 5
      RabbitMQ__PreFetchCount__modemlog: 5
      RabbitMQ__PreFetchCount__mysqlsingle: 1
      RabbitMQ__PreFetchCount__mysqlbulk: 5
      RabbitMQ__PreFetchCount__mddbulk: 5
      RabbitMQ__PreFetchCount__instantvaluesbulk: 5
      RabbitMQ__PreFetchCount__exportindexbulk: 5
      RabbitMQ__PreFetchCount__gprssignalqualitybulk: 5
      RabbitMQ__PreFetchCount__harmonicsthdbulk: 5
      RabbitMQ__PreFetchCount__harmonicscurrentspectrumbulk: 5
      RabbitMQ__PreFetchCount__harmonicsvoltagespectrumbulk: 5
      RabbitMQ__PreFetchCount__pvabulk: 5
      RabbitMQ__PreFetchCount__pvasingle: 1
  sp-taskscheduler:
    <<: *common-podman-service
    image: "docker.io/erte33/sp-taskscheduler:latest"
    volumes:
      - ./entrypoint.sh:/App/entrypoint.sh:Z
    entrypoint: ["bash", "-c", "/App/entrypoint.sh GrupArGe.SmartPower.TaskSchedulerService.dll"]
    environment:
      <<: [*dotnet-env, *rabbitmq-settings, *mqtt-settings]
      CheckCosa__CosaUrl: "https://kiwi.cosa.com.tr"
      CheckCosa__CosaloginPath: "/api/users/login"
      CheckCosa__CosaEndpointPath: "/api/endpoints/getEndpoints"
      CheckRelayLockStatus__lockedStatusValue: "4"
      CheckRelayLockStatus__deviceSatusParamId: "48"
      CheckRelayLockStatus__relayLockedAlarmId: "21"
      PROXY_SET: "0"
      PROXY_HOST: "192.168.1.1"
      PROXY_PORT: "8080"
      XML_SENT_SERVLET: "http://www.biotekno.biz:8080/SMS-Web/xmlsms"
      XML_REPORT_SERVLET: "http://www.biotekno.biz:8080/SMS-Web/xmlreport"
      REPORT_TIME_OUT: "30"
      iot_service_domain: "http://sp-iot:4444"

  sp-mqtt:
    <<: *common-podman-service
    image: "docker.io/erte33/sp-mqttserver:latest"
    container_name: sp-mqttserver
    expose:
      - "1883"
      - "1884"
    volumes:
      - ./entrypoint.sh:/App/entrypoint.sh:Z
    entrypoint: ["bash", "-c", "/App/entrypoint.sh Web.Server.dll"]
    environment:
      Authorize__ClientRequired: false
      ConnectionStrings__Mysql: *mysql-mqtt-connection
      <<: *mqtt-server-settings
  mysql:
    <<: *common-podman-service
    image: docker.io/mysql:8.0.33
    command:
      - --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
      - --skip-log-bin
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      TZ: Europe/Istanbul
    volumes:
      - ./sp-mysql8-data:/var/lib/mysql:Z
    cap_add:
      - SYS_NICE # CAP_SYS_NICE

  phpmyadmin:
    <<: *common-podman-service
    image: docker.io/phpmyadmin
    depends_on:
      - mysql
    expose:
      - "8080"
    environment:
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 10M
      PMA_HOST: ${MYSQL_HOST}
      APACHE_PORT: 8080

  rabbitmq:
    <<: *common-podman-service
    image: "docker.io/rabbitmq:4.1.0-management-alpine"
    expose:
      - "5672"
      - "15672" # RabbitMQ management UI port
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ./sp-rabbitmq-data:/var/lib/rabbitmq:Z

  mongo:
    <<: *common-podman-service
    image: docker.io/mongo:4.4.25 #8.0.5-rc2-noble
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    volumes:
      - ./sp-mongo-data:/data/db:Z

  mongo-express:
    <<: *common-podman-service
    image: docker.io/mongo-express:1.0.2-20-alpine3.19
    depends_on:
      - mongo
    container_name: sp-mongo-express
    expose:
      - "8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: ${MONGODB_HOST}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: ${ME_CONFIG_MONGODB_ENABLE_ADMIN}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
  waiter:
    <<: *common-podman-service
    image: docker.io/erte33/sp-waiter:latest
    build: ./waiter
    depends_on:
      - mysql
      - mongo
      - rabbitmq
    expose:
      - "4441"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MONGODB_HOST: ${MONGODB_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MONGODB_ROOT_USER: ${MONGODB_ROOT_USER}
      MONGODB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
