version: "3.9"
services:
  db:
    image: mysql:8.0
    volumes:
      - gruparge_db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    command:
      - --default-authentication-plugin=mysql_native_password
      - --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
      # - --max_execution_time=300
      # - --net_buffer_length=8K
      - --key_buffer_size=256M
      - --tmp_table_size=128M
      - --innodb_buffer_pool_size=512M
      # - --max_connections=100
      - --skip-log-bin
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - gruparge_wordpress_data:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - "8010:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
volumes:
  gruparge_db_data: {}
  gruparge_wordpress_data: {}
