version: "3.3"
services:
  ftpserver:
    restart: always
    ports:
      - "2121-2130:2121-2130"
    volumes:
      - ./files:/tmp
      - ./gapps:/gapps
      - .:/app
    image: fclairamb/ftpserver
