services:
  portainer:
    image: portainer/portainer-ce
    restart: always
    ports:
      - 9000:9000
#      - 8000:8000
      - 9443:9443
    environment:
      - EDGE_INSECURE_POLL=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
