version: "3.3"
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    network_mode: "host"
    volumes:
      - ./podman_portainer_data:/data:Z
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
    environment:
      - EDGE_INSECURE_POLL=1
