version: "3.2"
services:
  moga:
    # image: mattermost/mattermost-preview:latest
    # image: mattermost/mattermost-team-edition:6.0.0
    image: mattermost/mattermost-team-edition:9.0.0
    restart: always
    ports:
      - 8065:8065
      # - 8066:3306
    depends_on:
      - db
    volumes:
      # - ./mattermost-mysql:/var/lib/mysql
      - ./mattermost-data:/mattermost/data
      - ./mattermost-config:/mattermost/config
    environment:
      TZ: Asia/Istanbul
      MM_SQLSETTINGS_DRIVERNAME: mysql
      MM_SQLSETTINGS_DATASOURCE: mmuser:mostest@tcp(db:3306)/mattermost_test?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s
  db:
    image: mysql/mysql-server:5.7
    # ports:
    #   - 3306:3306
    volumes:
      - ./mattermost-mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mostest
      - MYSQL_USER=mmuser
      - MYSQL_PASSWORD=mostest
      - MYSQL_DATABASE=mattermost_test
