version: "3.2"
services:
  db:
    image: mysql:5.6.22
    # command:
    #- --default-authentication-plugin=mysql_native_password
    #- --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    # - --max_connections=1000
    # - --skip-log-bin
    # restart: always
    ports:
      - 3309:3306
    # volumes:
    #   - ./mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: mrrobot
      MYSQL_PASSWORD: mrrobot
      # TZ: Asia/Istanbul
    # cap_add:
    #   - SYS_NICE # CAP_SYS_NICE
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 3307:8080
